/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as InscriptionRouteImport } from './routes/inscription'
import { Route as AttenteRouteImport } from './routes/attente'
import { Route as JoueurRouteRouteImport } from './routes/joueur/route'
import { Route as CoachRouteRouteImport } from './routes/coach/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as JoueurIndexRouteImport } from './routes/joueur/index'
import { Route as CoachIndexRouteImport } from './routes/coach/index'
import { Route as JoueurStatsRouteImport } from './routes/joueur/stats'
import { Route as JoueurProgrammeRouteImport } from './routes/joueur/programme'
import { Route as JoueurProfilRouteImport } from './routes/joueur/profil'
import { Route as CoachStatsRouteImport } from './routes/coach/stats'
import { Route as CoachSemaineRouteImport } from './routes/coach/semaine'
import { Route as CoachSeancesRouteImport } from './routes/coach/seances'
import { Route as CoachProgrammesRouteImport } from './routes/coach/programmes'
import { Route as CoachPlanningRouteImport } from './routes/coach/planning'
import { Route as CoachJoueursRouteImport } from './routes/coach/joueurs'
import { Route as CoachBiblioRouteImport } from './routes/coach/biblio'
import { Route as CoachAnnonceRouteImport } from './routes/coach/annonce'

const InscriptionRoute = InscriptionRouteImport.update({
  id: '/inscription',
  path: '/inscription',
  getParentRoute: () => rootRouteImport,
} as any)
const AttenteRoute = AttenteRouteImport.update({
  id: '/attente',
  path: '/attente',
  getParentRoute: () => rootRouteImport,
} as any)
const JoueurRouteRoute = JoueurRouteRouteImport.update({
  id: '/joueur',
  path: '/joueur',
  getParentRoute: () => rootRouteImport,
} as any)
const CoachRouteRoute = CoachRouteRouteImport.update({
  id: '/coach',
  path: '/coach',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const JoueurIndexRoute = JoueurIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => JoueurRouteRoute,
} as any)
const CoachIndexRoute = CoachIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => CoachRouteRoute,
} as any)
const JoueurStatsRoute = JoueurStatsRouteImport.update({
  id: '/stats',
  path: '/stats',
  getParentRoute: () => JoueurRouteRoute,
} as any)
const JoueurProgrammeRoute = JoueurProgrammeRouteImport.update({
  id: '/programme',
  path: '/programme',
  getParentRoute: () => JoueurRouteRoute,
} as any)
const JoueurProfilRoute = JoueurProfilRouteImport.update({
  id: '/profil',
  path: '/profil',
  getParentRoute: () => JoueurRouteRoute,
} as any)
const CoachStatsRoute = CoachStatsRouteImport.update({
  id: '/stats',
  path: '/stats',
  getParentRoute: () => CoachRouteRoute,
} as any)
const CoachSemaineRoute = CoachSemaineRouteImport.update({
  id: '/semaine',
  path: '/semaine',
  getParentRoute: () => CoachRouteRoute,
} as any)
const CoachSeancesRoute = CoachSeancesRouteImport.update({
  id: '/seances',
  path: '/seances',
  getParentRoute: () => CoachRouteRoute,
} as any)
const CoachProgrammesRoute = CoachProgrammesRouteImport.update({
  id: '/programmes',
  path: '/programmes',
  getParentRoute: () => CoachRouteRoute,
} as any)
const CoachPlanningRoute = CoachPlanningRouteImport.update({
  id: '/planning',
  path: '/planning',
  getParentRoute: () => CoachRouteRoute,
} as any)
const CoachJoueursRoute = CoachJoueursRouteImport.update({
  id: '/joueurs',
  path: '/joueurs',
  getParentRoute: () => CoachRouteRoute,
} as any)
const CoachBiblioRoute = CoachBiblioRouteImport.update({
  id: '/biblio',
  path: '/biblio',
  getParentRoute: () => CoachRouteRoute,
} as any)
const CoachAnnonceRoute = CoachAnnonceRouteImport.update({
  id: '/annonce',
  path: '/annonce',
  getParentRoute: () => CoachRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/coach': typeof CoachRouteRouteWithChildren
  '/joueur': typeof JoueurRouteRouteWithChildren
  '/attente': typeof AttenteRoute
  '/inscription': typeof InscriptionRoute
  '/coach/annonce': typeof CoachAnnonceRoute
  '/coach/biblio': typeof CoachBiblioRoute
  '/coach/joueurs': typeof CoachJoueursRoute
  '/coach/planning': typeof CoachPlanningRoute
  '/coach/programmes': typeof CoachProgrammesRoute
  '/coach/seances': typeof CoachSeancesRoute
  '/coach/semaine': typeof CoachSemaineRoute
  '/coach/stats': typeof CoachStatsRoute
  '/joueur/profil': typeof JoueurProfilRoute
  '/joueur/programme': typeof JoueurProgrammeRoute
  '/joueur/stats': typeof JoueurStatsRoute
  '/coach/': typeof CoachIndexRoute
  '/joueur/': typeof JoueurIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/attente': typeof AttenteRoute
  '/inscription': typeof InscriptionRoute
  '/coach/annonce': typeof CoachAnnonceRoute
  '/coach/biblio': typeof CoachBiblioRoute
  '/coach/joueurs': typeof CoachJoueursRoute
  '/coach/planning': typeof CoachPlanningRoute
  '/coach/programmes': typeof CoachProgrammesRoute
  '/coach/seances': typeof CoachSeancesRoute
  '/coach/semaine': typeof CoachSemaineRoute
  '/coach/stats': typeof CoachStatsRoute
  '/joueur/profil': typeof JoueurProfilRoute
  '/joueur/programme': typeof JoueurProgrammeRoute
  '/joueur/stats': typeof JoueurStatsRoute
  '/coach': typeof CoachIndexRoute
  '/joueur': typeof JoueurIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/coach': typeof CoachRouteRouteWithChildren
  '/joueur': typeof JoueurRouteRouteWithChildren
  '/attente': typeof AttenteRoute
  '/inscription': typeof InscriptionRoute
  '/coach/annonce': typeof CoachAnnonceRoute
  '/coach/biblio': typeof CoachBiblioRoute
  '/coach/joueurs': typeof CoachJoueursRoute
  '/coach/planning': typeof CoachPlanningRoute
  '/coach/programmes': typeof CoachProgrammesRoute
  '/coach/seances': typeof CoachSeancesRoute
  '/coach/semaine': typeof CoachSemaineRoute
  '/coach/stats': typeof CoachStatsRoute
  '/joueur/profil': typeof JoueurProfilRoute
  '/joueur/programme': typeof JoueurProgrammeRoute
  '/joueur/stats': typeof JoueurStatsRoute
  '/coach/': typeof CoachIndexRoute
  '/joueur/': typeof JoueurIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/coach'
    | '/joueur'
    | '/attente'
    | '/inscription'
    | '/coach/annonce'
    | '/coach/biblio'
    | '/coach/joueurs'
    | '/coach/planning'
    | '/coach/programmes'
    | '/coach/seances'
    | '/coach/semaine'
    | '/coach/stats'
    | '/joueur/profil'
    | '/joueur/programme'
    | '/joueur/stats'
    | '/coach/'
    | '/joueur/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/attente'
    | '/inscription'
    | '/coach/annonce'
    | '/coach/biblio'
    | '/coach/joueurs'
    | '/coach/planning'
    | '/coach/programmes'
    | '/coach/seances'
    | '/coach/semaine'
    | '/coach/stats'
    | '/joueur/profil'
    | '/joueur/programme'
    | '/joueur/stats'
    | '/coach'
    | '/joueur'
  id:
    | '__root__'
    | '/'
    | '/coach'
    | '/joueur'
    | '/attente'
    | '/inscription'
    | '/coach/annonce'
    | '/coach/biblio'
    | '/coach/joueurs'
    | '/coach/planning'
    | '/coach/programmes'
    | '/coach/seances'
    | '/coach/semaine'
    | '/coach/stats'
    | '/joueur/profil'
    | '/joueur/programme'
    | '/joueur/stats'
    | '/coach/'
    | '/joueur/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CoachRouteRoute: typeof CoachRouteRouteWithChildren
  JoueurRouteRoute: typeof JoueurRouteRouteWithChildren
  AttenteRoute: typeof AttenteRoute
  InscriptionRoute: typeof InscriptionRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/inscription': {
      id: '/inscription'
      path: '/inscription'
      fullPath: '/inscription'
      preLoaderRoute: typeof InscriptionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/attente': {
      id: '/attente'
      path: '/attente'
      fullPath: '/attente'
      preLoaderRoute: typeof AttenteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/joueur': {
      id: '/joueur'
      path: '/joueur'
      fullPath: '/joueur'
      preLoaderRoute: typeof JoueurRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/coach': {
      id: '/coach'
      path: '/coach'
      fullPath: '/coach'
      preLoaderRoute: typeof CoachRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/joueur/': {
      id: '/joueur/'
      path: '/'
      fullPath: '/joueur/'
      preLoaderRoute: typeof JoueurIndexRouteImport
      parentRoute: typeof JoueurRouteRoute
    }
    '/coach/': {
      id: '/coach/'
      path: '/'
      fullPath: '/coach/'
      preLoaderRoute: typeof CoachIndexRouteImport
      parentRoute: typeof CoachRouteRoute
    }
    '/joueur/stats': {
      id: '/joueur/stats'
      path: '/stats'
      fullPath: '/joueur/stats'
      preLoaderRoute: typeof JoueurStatsRouteImport
      parentRoute: typeof JoueurRouteRoute
    }
    '/joueur/programme': {
      id: '/joueur/programme'
      path: '/programme'
      fullPath: '/joueur/programme'
      preLoaderRoute: typeof JoueurProgrammeRouteImport
      parentRoute: typeof JoueurRouteRoute
    }
    '/joueur/profil': {
      id: '/joueur/profil'
      path: '/profil'
      fullPath: '/joueur/profil'
      preLoaderRoute: typeof JoueurProfilRouteImport
      parentRoute: typeof JoueurRouteRoute
    }
    '/coach/stats': {
      id: '/coach/stats'
      path: '/stats'
      fullPath: '/coach/stats'
      preLoaderRoute: typeof CoachStatsRouteImport
      parentRoute: typeof CoachRouteRoute
    }
    '/coach/semaine': {
      id: '/coach/semaine'
      path: '/semaine'
      fullPath: '/coach/semaine'
      preLoaderRoute: typeof CoachSemaineRouteImport
      parentRoute: typeof CoachRouteRoute
    }
    '/coach/seances': {
      id: '/coach/seances'
      path: '/seances'
      fullPath: '/coach/seances'
      preLoaderRoute: typeof CoachSeancesRouteImport
      parentRoute: typeof CoachRouteRoute
    }
    '/coach/programmes': {
      id: '/coach/programmes'
      path: '/programmes'
      fullPath: '/coach/programmes'
      preLoaderRoute: typeof CoachProgrammesRouteImport
      parentRoute: typeof CoachRouteRoute
    }
    '/coach/planning': {
      id: '/coach/planning'
      path: '/planning'
      fullPath: '/coach/planning'
      preLoaderRoute: typeof CoachPlanningRouteImport
      parentRoute: typeof CoachRouteRoute
    }
    '/coach/joueurs': {
      id: '/coach/joueurs'
      path: '/joueurs'
      fullPath: '/coach/joueurs'
      preLoaderRoute: typeof CoachJoueursRouteImport
      parentRoute: typeof CoachRouteRoute
    }
    '/coach/biblio': {
      id: '/coach/biblio'
      path: '/biblio'
      fullPath: '/coach/biblio'
      preLoaderRoute: typeof CoachBiblioRouteImport
      parentRoute: typeof CoachRouteRoute
    }
    '/coach/annonce': {
      id: '/coach/annonce'
      path: '/annonce'
      fullPath: '/coach/annonce'
      preLoaderRoute: typeof CoachAnnonceRouteImport
      parentRoute: typeof CoachRouteRoute
    }
  }
}

interface CoachRouteRouteChildren {
  CoachAnnonceRoute: typeof CoachAnnonceRoute
  CoachBiblioRoute: typeof CoachBiblioRoute
  CoachJoueursRoute: typeof CoachJoueursRoute
  CoachPlanningRoute: typeof CoachPlanningRoute
  CoachProgrammesRoute: typeof CoachProgrammesRoute
  CoachSeancesRoute: typeof CoachSeancesRoute
  CoachSemaineRoute: typeof CoachSemaineRoute
  CoachStatsRoute: typeof CoachStatsRoute
  CoachIndexRoute: typeof CoachIndexRoute
}

const CoachRouteRouteChildren: CoachRouteRouteChildren = {
  CoachAnnonceRoute: CoachAnnonceRoute,
  CoachBiblioRoute: CoachBiblioRoute,
  CoachJoueursRoute: CoachJoueursRoute,
  CoachPlanningRoute: CoachPlanningRoute,
  CoachProgrammesRoute: CoachProgrammesRoute,
  CoachSeancesRoute: CoachSeancesRoute,
  CoachSemaineRoute: CoachSemaineRoute,
  CoachStatsRoute: CoachStatsRoute,
  CoachIndexRoute: CoachIndexRoute,
}

const CoachRouteRouteWithChildren = CoachRouteRoute._addFileChildren(
  CoachRouteRouteChildren,
)

interface JoueurRouteRouteChildren {
  JoueurProfilRoute: typeof JoueurProfilRoute
  JoueurProgrammeRoute: typeof JoueurProgrammeRoute
  JoueurStatsRoute: typeof JoueurStatsRoute
  JoueurIndexRoute: typeof JoueurIndexRoute
}

const JoueurRouteRouteChildren: JoueurRouteRouteChildren = {
  JoueurProfilRoute: JoueurProfilRoute,
  JoueurProgrammeRoute: JoueurProgrammeRoute,
  JoueurStatsRoute: JoueurStatsRoute,
  JoueurIndexRoute: JoueurIndexRoute,
}

const JoueurRouteRouteWithChildren = JoueurRouteRoute._addFileChildren(
  JoueurRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CoachRouteRoute: CoachRouteRouteWithChildren,
  JoueurRouteRoute: JoueurRouteRouteWithChildren,
  AttenteRoute: AttenteRoute,
  InscriptionRoute: InscriptionRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
